### ISSUE TITLE
Issue with solidity arrays when trying to deploy and interact with graphql playground 

### ISSUE THREAD

**Issue by aion-ollie** [titan-suite/ide-alpha#1]
Contract code:
```
pragma solidity ^0.4.9;


contract ExampleTwo {
    struct Container {
        uint128[] arr;
    }  

    Container container = Container(new uint128[](0));

    function read() public returns(uint128[]) {
        return container.arr;
    }
    
    function write(uint128 item) public {
        container.arr.push(item);
    }

}
```

GraphQL:
```
query { 
  read{
    uint128Arr_0{
      int
      string
    }
  }
} 
```
At first I was not able to deploy, but restarting the server helped. Then once I deployed the contract when I try to query the read function I get the following error:
```
{
  "data": {
    "read": {
      "uint128Arr_0": null
    }
  },
  "errors": [
    {
      "message": "Expected Iterable, but did not find one for field read.uint128Arr_0.",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "read",
        "uint128Arr_0"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Expected Iterable, but did not find one for field read.uint128Arr_0.",
            "    at invariant (/Users/ollie/Aion/server/node_modules/graphql/jsutils/invariant.js:19:11)",
            "    at completeListValue (/Users/ollie/Aion/server/node_modules/graphql/execution/execute.js:673:65)",
            "    at completeValue (/Users/ollie/Aion/server/node_modules/graphql/execution/execute.js:643:12)",
            "    at completeValueWithLocatedError (/Users/ollie/Aion/server/node_modules/graphql/execution/execute.js:580:21)",
            "    at completeValueCatchingError (/Users/ollie/Aion/server/node_modules/graphql/execution/execute.js:556:21)",
            "    at resolveField (/Users/ollie/Aion/server/node_modules/graphql/execution/execute.js:497:10)",
            "    at /Users/ollie/Aion/server/node_modules/graphql/execution/execute.js:364:18",
            "    at Array.reduce (<anonymous>)",
            "    at executeFields (/Users/ollie/Aion/server/node_modules/graphql/execution/execute.js:361:42)",
            "    at collectAndExecuteSubfields (/Users/ollie/Aion/server/node_modules/graphql/execution/execute.js:772:10)",
            "    at completeObjectValue (/Users/ollie/Aion/server/node_modules/graphql/execution/execute.js:762:10)",
            "    at completeValue (/Users/ollie/Aion/server/node_modules/graphql/execution/execute.js:660:12)",
            "    at /Users/ollie/Aion/server/node_modules/graphql/execution/execute.js:617:14",
            "    at <anonymous>",
            "    at process._tickDomainCallback (internal/process/next_tick.js:228:7)"
          ]
        }
      }
    }
  ]
}
```

**Comment by gptguy** [comment]
Hi @aion-ollie, Issue fixed in  [#e5be079](https://github.com/titan-suite/Aion-to-GraphQL/commit/e5be07906b1267670ea37c8e52344bdece6e20f3)and a patched version has been released for [ABI parser](https://www.npmjs.com/package/@titan-suite/aion-to-graphql). Please run `npm update`.
